name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: hydrosquall/repo-visualizer@cameron.yick/feature/ignore-files-and-folders
        with:
          excluded_paths: "docs,.vscode,.gitignore,.nvmrc,.prettierrc"
          excluded_globs: "scripts/*.svg"
          commit_message: "Update diagram [skip ci]"
          root_path: "./src/components/"
